sudo: required
services:
  - docker

before_install:
  - docker build -t danielcortes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run danielcortes/react-test npm test -- --coverage

after_success:
  - docker build -t danielcortes/multi-client ./client
  - docker build -t danielcortes/multi-nginx ./nginx
  - docker build -t danielcortes/multi-server ./server
  - docker build -t danielcortes/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push danielcortes/multi-client
  - docker push danielcortes/multi-nginx
  - docker push danielcortes/multi-server
  - docker push danielcortes/multi-worker
